namespace BusinessService.Application.DTOs;

public record BusinessDto(
    Guid Id,
    string Name,
    string? Website,
    bool IsBranch,
    decimal AvgRating,
    long ReviewCount,
    Guid? ParentBusinessId,
    List<CategoryDto> Categories,
    string? BusinessAddress,
    string? Logo,
    Dictionary<string, string>? OpeningHours,
    string? BusinessEmail,
    string? BusinessPhoneNumber,
    string? CacNumber,
    string? AccessUsername,
    string? AccessNumber,
    Dictionary<string, string>? SocialMediaLinks,
    string? BusinessDescription,
    List<string>? Media,
    bool IsVerified,
    string? ReviewLink,
    string? PreferredContactMethod,
    string[]? Highlights,
    List<TagDto>? Tags,
    string? AverageResponseTime,
    long ProfileClicks,
    List<FaqDto>? Faqs,
    string? QrCodeBase64,
    string? BusinessStatus,
    string? BusinessStreet,
    string? BusinessCityTown,
    string? BusinessState,
    string? ReviewSummary,
    bool IdVerified,
    string? IdVerificationType,
    decimal? BayesianAverage
);